/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;


import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import conexion.bd;

/**
 *
 * @author daniel
 */
public class docente extends javax.swing.JFrame {

    /**
     * Creates new form docente
     */
    private Connection cn;
    private FileInputStream fi;
    private long longitudBits;
    
    public docente() {
        initComponents();
        cn = null;
        setLocationRelativeTo(null);
        
    }
    //actualiza la conexion
    public void setConexion(Connection cn){
        this.cn = cn;
        TablaDocumentos();
    }
    public int  grabar(String nombre,FileInputStream documento,long longitud){

        int rsu = 0;
        String sql = "INSERT INTO documentos(nombredocumento,documento) VALUES (?,?)";
        if(cn == null){
            JOptionPane.showMessageDialog(null, "no se puedo conectar con la base de datos");
        }else{
            try{
                 PreparedStatement ps = cn.prepareStatement(sql);
                 ps.setString(1,nombre);
                 ps.setBlob(2,documento,longitud);
                 rsu = ps.executeUpdate();
            }catch(SQLException ex){
                ex.printStackTrace();
            }finally{
                TablaDocumentos();
            }
        }
        return rsu;
    }
 
    
    public void TablaDocumentos(){
        //creacion de la tabla de datos para empleados
            DefaultTableModel tabla = new DefaultTableModel();
            tabla.addColumn("ID");
            tabla.addColumn("Nombre");
        
            tableDocument.setModel(tabla);
            String sql = "SELECT * FROM documentos";
            String datos[] = new String[2];
            Statement sd;
            try {            
                sd = cn.createStatement();
                ResultSet sf = sd.executeQuery(sql);
                while(sf.next()){
                    datos[0] = String.valueOf(sf.getInt(1));
                    datos[1] = sf.getString(2);
                    
                    tabla.addRow(datos);
                }
                tableDocument.setModel(tabla);
            } 
            catch (SQLException ex) {
                ex.printStackTrace();
            }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        btnNotificacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDocument = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setText("Cerrar sesion");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        btnSubir.setText("Subir Documento");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        btnNotificacion.setText("Notificacion");
        btnNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 120, -1));

        jButton1.setText("Estudiantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, -1));

        tableDocument.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableDocument);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 71, 363, 410));

        jLabel1.setText("lista de documentos subidos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 242, 24));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
         try {
            cn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            login l = new login();
            l.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed

        //codigo para insertar en la base de datos
        File archivo;
        JFileChooser se = new JFileChooser();
        se.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int estado = se.showOpenDialog(null);
        if(estado == JFileChooser.APPROVE_OPTION){
            try {
                archivo = se.getSelectedFile();
                fi = new FileInputStream(se.getSelectedFile());//archivo seleccionado
                //averiguamos cantidad de bits
                this.longitudBits = archivo.length();
                if(grabar(archivo.getName(),fi,longitudBits)!=0){
                    JOptionPane.showMessageDialog(null,"Se ha subido el documento");
                }else{
                    JOptionPane.showMessageDialog(null,"Fallo al subir el documento");
                } 
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "archivo no seleccionado");
        }
       
    }//GEN-LAST:event_btnSubirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //dirige a los estudiantes en el curso
        listaestudiantes le = new listaestudiantes();
        le.setConexion (cn);
        le.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionActionPerformed
        // TODO add your handling code here:
        notificacion le = new notificacion();
        le.setConexion (cn);
        le.setVisible(true);
    }//GEN-LAST:event_btnNotificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new docente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNotificacion;
    private javax.swing.JButton btnSubir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDocument;
    // End of variables declaration//GEN-END:variables
}
