/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import conexion.bd;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    private Connection cn ;
    public login() {
        initComponents();
        cn = new bd().conectar();
        setLocationRelativeTo(null);
    }
    boolean ingresarDocente(String Usuario, String Contraseña){
        boolean ver = false;
        int respuesta = 0;
        String sql = "SELECT count(*) FROM docente WHERE usuarioDoc = '" + Usuario + "'AND  contraseniaDoc = '" + Contraseña + "' ";
            Statement sd;
            try {
                sd = cn.createStatement();
                ResultSet sf = sd.executeQuery(sql);
                while(sf.next()){
                   respuesta = sf.getInt(1); } 
                 if(respuesta == 1){
                        ver = true;}
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);}
            return ver;
    }
    
    boolean ingresarEstudiante(String Usuario, String Contraseña){
        boolean ver = false;
        int respuesta;
        String sql = "SELECT count(*) FROM estudiante WHERE usuarioEst = '" + Usuario + "'AND  contraseniaEst = '" + Contraseña + "' ";
        Statement sd;
        try {
            sd = cn.createStatement();
            ResultSet sf = sd.executeQuery(sql);
            while (sf.next()) {                
                respuesta = sf.getInt(1);
                if (respuesta == 1) {
                    ver = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        return ver;
    }
    
    boolean ingresarAuxiliar(String Usuario, String Contraseña){
        boolean ver = false;
        int respuesta;
        String sql = "SELECT count(*) FROM auxiliar WHERE usuarioAux = '" + Usuario + "'AND  contraseniaAux = '" + Contraseña + "' ";
        Statement sd;
        try {
            sd = cn.createStatement();
            ResultSet sf = sd.executeQuery(sql);
            while (sf.next()) {                
                respuesta = sf.getInt(1);
                if (respuesta == 1) {
                    ver = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        return ver;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jComboBoxLogin = new javax.swing.JComboBox();
        jLabelContra = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLogin.setText("login");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 64, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 170, -1));

        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jComboBoxLogin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Docente", "Auxiliar", "Estudiante" }));
        jComboBoxLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 170, 25));

        jLabelContra.setText("Contraseña");
        getContentPane().add(jLabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 260, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 260, -1));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/info_sistemas.png"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 730, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       //agarramos los datos de ingreso
       String usuario = jTextFieldUsuario.getText();
       String contraseña = String.valueOf(jPasswordField.getPassword());
       String Item = jComboBoxLogin.getSelectedItem().toString();
       if(Item.equals("Docente")){
           if(ingresarDocente(usuario,contraseña) == true){
            docente d = new docente();
            d.setConexion (cn);
            d.setVisible(true);
            this.dispose();
           }else{
            JOptionPane.showMessageDialog(null, "No existe el usuario al que trato de ingresar");
           }
       }else{
           if(Item.equals("Auxiliar")){
               if (ingresarAuxiliar(usuario, contraseña)== true) {
                   auxiliar a = new auxiliar();
                   a.setConexion (cn);
                   a.setVisible(true);
                   this.dispose();
               } else {
                   JOptionPane.showMessageDialog(null, "No existe el usuario al que trato de ingresar");
               }
           }else{
            if(Item.equals("Estudiante")){
                if (ingresarEstudiante(usuario, contraseña)== true) {
                    estudiante e = new estudiante();
                    e.setConexion (cn);
                    e.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No existe el usuario al que trato de ingresar");
                }
            }
           }
       }
       
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jComboBoxLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLoginActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox jComboBoxLogin;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
